export const Films =[
    {id: 1, name: 'Spider-Man: Across the Spider-Verse', length: '2h 20m', year: '2023', img:'assets/images/sats.jpg', info:'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.', clip:'https://www.youtube.com/embed/cqGjhVJWtEg', tagline:'It`s how you wear the mask that matters'},
    {id: 2, name: 'John Wick: Chapter 4', length:'2h 49m', year: '2023', img:'assets/images/jw4.jpg', info:'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.', clip:'https://www.youtube.com/embed/qEVUtrk8_B4', tagline:'No way back, one way out.'},
    {id: 3, name: 'RRR', length:'3h 7m', year: '2022', img:'assets/images/rrr.jpg', info:'A fearless revolutionary and an officer in the British force, who once shared a deep bond, decide to join forces and chart out an inspirational path of freedom against the despotic rulers.', clip:'https://www.youtube.com/embed/NgBoMJy386M', tagline:'Rise, Roar, Revolt.'},
    {id: 4, name: 'Ready Player One', length:'2h 20m', year: '2018',img:'assets/images/rpo.jpg', info:'When the creator of a virtual reality called the OASIS dies, he makes a posthumous challenge to all OASIS users to find his Easter Egg, which will give the finder his fortune and control of his world.', clip:'https://www.youtube.com/embed/cSp1dM2Vj48', tagline:'A better reality awaits.'},
    {id: 5, name: 'Kingsman: The Secret Service', length: '2h 9m', year: '2014',img:'assets/images/ktss.jpg', info:'Gary `Eggsy` Unwin faces several challenges when he gets recruited as a secret agent in a secret spy organisation in order to look for Richmond Valentine, an eco-terrorist.', clip:'https://www.youtube.com/embed/kl8F-8tR8to', tagline:'Manners maketh man.' },
    {id: 6, name: 'TRON: Legacy', length: '2h 5m', year: '2010', img:'assets/images/tl.jpg', info:'The son of a virtual world designer goes looking for his father and ends up inside the digital world that his father designed. He meets his father`s corrupted creation and a unique ally who was born inside the digital world.', clip:'https://www.youtube.com/embed/L9szn1QQfas', tagline:'The game has changed.'},
    {id: 7, name: 'Edge of Tomorrow', length:'1h 53m', year: '2014', img:'assets/images/eot.jpg', info:'With the help of warrior Rita Vrataski, Major William Cage has to save Earth and the human race from an alien species, after being caught in a time loop.', clip:'https://www.youtube.com/embed/yUmSVcttXnI', tagline:'Live. Die. Repeat.'},
    {id: 8, name: 'Iron Man 3', length:'2h 10m', year: '2013', img:'assets/images/im3.jpg', info: 'Tony Stark encounters a formidable foe called the Mandarin. After failing to defeat his enemy, Tony embarks on a journey of self-discovery as he fights against the powerful Mandarin.', clip:'https://www.youtube.com/embed/f_h95mEd4TI', tagline:'Unleash the power behind the armor.'},
    {id: 9, name: 'G.I. Joe: Retaliation', length:'1h 50m', year: '2013', img:'assets/images/gij.jpg', info: 'The Joes are declared traitors by Zartan, and the Cobra Commander now has all the world leaders under his control. With nowhere to go, the remaining Joes turn to their original leader, General Colton.', clip:'https://www.youtube.com/embed/2vAo4rJPqQ4'}
  ];